[2024-08-07 20:09:07.740] RUN   (taps.run) :: CLI Arguments: --config configs/moldesign-app.toml configs/dask-local.toml configs/proxystore-redis-local.toml
[2024-08-07 20:09:07.749] RUN   (taps.run) :: Environment:
host: x1921c0s6b0n0
  os: linux (Linux-5.14.21-150400.24.55-default-x86_64-with-glibc2.31)
  cpu: x86_64 (104 cores / 208 logical)
  memory: 1203.76 GB
python:
  version: 3.11.9
  build: CPython (64-bit runtime) [GCC 11.2.0]
  taps: 0.2.1.dev1
[2024-08-07 20:09:07.750] RUN   (taps.run) :: Starting app (name=moldesign)
[2024-08-07 20:09:07.751] RUN   (taps.run) :: Configuration:
app:
  name: 'moldesign'
  batch_size: 32
  dataset: '/lus/gila/projects/CSC249ADCD08_CNDA/jgpaul/hppss24-proxystore/experiments/data/moldesign/QM9-search.tsv'
  initial_count: 32
  search_count: 128
  seed: 0
engine:
  executor:
    name: 'dask'
    daemon_workers: False
    scheduler: None
    use_threads: False
    workers: 32
  filter:
    name: 'object-type'
    patterns: ['.*array', 'Client', 'Result', 'Pipeline']
  task_record_file_name: 'tasks.jsonl'
  transformer:
    name: 'proxystore'
    cache_size: 16
    connector:
      kind: 'redis'
      options:
        hostname: 'localhost'
        port: 6379
    extract_target: True
    populate_target: True
logging:
  file_level: 'INFO'
  file_name: 'log.txt'
  level: 'INFO'
run:
  dir_format: 'runs/{name}/proxystore/{timestamp}'
  env_vars:
    OMP_NUM_THREADS: '1'
version: '0.2.1.dev1'
[2024-08-07 20:09:07.751] RUN   (taps.run) :: Runtime directory: /lus/gila/projects/CSC249ADCD08_CNDA/jgpaul/hppss24-proxystore/experiments/runs/moldesign/proxystore/2024-08-07-20-09-07
[2024-08-07 20:09:09.640] INFO  (proxystore.store) :: Registered a store named "proxy-transformer"
[2024-08-07 20:09:09.641] INFO  (proxystore.store.base) :: Initialized Store(name=proxy-transformer, connector=RedisConnector(hostname=localhost, port=6379), serializer=default, deserializer=default, cache_size=16, metrics=False, populate_target=True, auto_register=True)
[2024-08-07 20:09:09.797] APP   (taps.apps.moldesign.app) :: Loaded search space (size=130,258)
[2024-08-07 20:09:09.805] APP   (taps.apps.moldesign.app) :: Submitted initial computations
[2024-08-07 20:09:09.805] INFO  (taps.apps.moldesign.app) :: Initial set: ['NC(=O)C12CN1C(=O)C2', 'CC12CCC(C1)C(=O)C2', 'CNC1=NC=NOC1=O', 'C1OC11CCCC1', 'COC12CCC1(O)C2O', 'OC1C=CC=CC=C1', 'CCC(C)C1COCO1', 'COC1=CC(C)=C(N)N1', 'CNC1=C(NC=N1)C=O', 'OCC1CC1OCC#C', 'OC1C=C2CN3C1C23', 'OC1CCC23CC12CO3', 'CCC1=COC=C1OC', 'CC1CCCCC(=O)C1', 'CC12OC3C4C(C14)C23', 'CC1OC2C3C1CC23O', 'OC12COC1C2(O)C=O', 'CC1CC(O)CC(=O)C1', 'O1C=CC2=C1N=CN=C2', 'O=C1OC2CC2(O1)C#C', 'CC1=COC2=C1OC=C2', 'CC(C)(C)CNCC#N', 'CC(O)C1=C(O)N=NO1', 'OC1CC2OCC2=C1', 'OCC(=O)N(C=N)C=N', 'O=C1NC2CC12C1CC1', 'CC1NC(=O)C1C(N)=O', 'CC12CN1CC2CO', 'CC1=NNC=N1', 'CC(O)C1C=CC2NC12', 'CCC#CC(C=O)C#N', 'CC1(CC1)C(C#C)C#N']
[2024-08-07 20:09:11.780] ERROR (taps.apps.moldesign.app) :: Simulation task failed... submitting new SMILE string
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 96, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 183, in _task_done_callback
    execution_info = future.result().info
                     ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:11.922] ERROR (taps.apps.moldesign.app) :: Simulation task failed... submitting new SMILE string
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 96, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:12.688] APP   (taps.apps.moldesign.app) :: Done computing initial set
[2024-08-07 20:09:12.689] APP   (taps.apps.moldesign.app) :: Created initial training set (size=32)
[2024-08-07 20:09:12.690] APP   (taps.apps.moldesign.app) :: Submitting inference tasks
[2024-08-07 20:09:16.782] APP   (taps.apps.moldesign.app) :: Inference results received (size=130258)
[2024-08-07 20:09:16.796] APP   (taps.apps.moldesign.app) :: Submitted new computations (size=32)
[2024-08-07 20:09:17.296] ERROR (root) :: Simulation task failed
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 169, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 183, in _task_done_callback
    execution_info = future.result().info
                     ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:17.353] ERROR (root) :: Simulation task failed
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 169, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 183, in _task_done_callback
    execution_info = future.result().info
                     ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:17.356] ERROR (root) :: Simulation task failed
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 169, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 183, in _task_done_callback
    execution_info = future.result().info
                     ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:17.363] ERROR (root) :: Simulation task failed
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 169, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:17.382] ERROR (root) :: Simulation task failed
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 169, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:17.390] ERROR (root) :: Simulation task failed
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 169, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 183, in _task_done_callback
    execution_info = future.result().info
                     ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:17.779] APP   (taps.apps.moldesign.app) :: Submitting inference tasks
[2024-08-07 20:09:22.170] APP   (taps.apps.moldesign.app) :: Inference results received (size=130258)
[2024-08-07 20:09:22.200] APP   (taps.apps.moldesign.app) :: Submitted new computations (size=32)
[2024-08-07 20:09:22.519] ERROR (root) :: Simulation task failed
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 169, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 183, in _task_done_callback
    execution_info = future.result().info
                     ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:23.144] APP   (taps.apps.moldesign.app) :: Submitting inference tasks
[2024-08-07 20:09:27.558] APP   (taps.apps.moldesign.app) :: Inference results received (size=130258)
[2024-08-07 20:09:27.583] APP   (taps.apps.moldesign.app) :: Submitted new computations (size=32)
[2024-08-07 20:09:27.858] ERROR (root) :: Simulation task failed
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 169, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 183, in _task_done_callback
    execution_info = future.result().info
                     ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:28.730] APP   (taps.apps.moldesign.app) :: Submitting inference tasks
[2024-08-07 20:09:33.372] APP   (taps.apps.moldesign.app) :: Inference results received (size=130258)
[2024-08-07 20:09:33.395] APP   (taps.apps.moldesign.app) :: Submitted new computations (size=32)
[2024-08-07 20:09:33.593] ERROR (root) :: Simulation task failed
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 169, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 183, in _task_done_callback
    execution_info = future.result().info
                     ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:33.647] ERROR (root) :: Simulation task failed
Traceback (most recent call last):
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/app.py", line 169, in run
    ie = future.result()
         ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 124, in result
    task_result = self.future.result(timeout=timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/distributed/client.py", line 405, in result
    return self.client.sync(self._result, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/_engine.py", line 183, in _task_done_callback
    execution_info = future.result().info
                     ^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/engine/task.py", line 176, in __call__
    result = self.function(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 109, in compute_vertical
    xyz = generate_initial_xyz(smiles)
      ^^^^^^^^^^^^^^^^^
  File "/home/jgpaul/.conda/envs/hppss24/lib/python3.11/site-packages/taps/apps/moldesign/chemfunctions.py", line 62, in generate_initial_xyz
    AllChem.MMFFOptimizeMolecule(mol)
      ^^^^^^^^^^^^^^^^^
ValueError: Bad Conformer Id
[2024-08-07 20:09:34.487] APP   (taps.apps.moldesign.app) :: Saved figure to /lus/gila/projects/CSC249ADCD08_CNDA/jgpaul/hppss24-proxystore/experiments/runs/moldesign/proxystore/2024-08-07-20-09-07/results.png
[2024-08-07 20:09:34.497] APP   (taps.apps.moldesign.app) :: Saved results to /lus/gila/projects/CSC249ADCD08_CNDA/jgpaul/hppss24-proxystore/experiments/runs/moldesign/proxystore/2024-08-07-20-09-07/results.csv
[2024-08-07 20:09:35.303] INFO  (proxystore.store) :: Unregistered a store named proxy-transformer
[2024-08-07 20:09:35.307] RUN   (taps.run) :: Finished app (name=moldesign, runtime=27.56s, tasks=426)
